### ISSUE TITLE
freezes card on

### ISSUE THREAD

**Issue by eskanndar** [saoudrizwan/CardSlider#2]
when trying to slide quickly on screen of my iPhone 6 (not on simulator) the card is freezed.
Any Idea?

**Comment by saoudrizwan** [comment]
@eskanndar It's probably due to the animation of the next cards coming forward still taking place. I'll look into a fix.

**Comment by eskanndar** [comment]
Can we suppress the animation for the 3 cards?

**Comment by saoudrizwan** [comment]
Just fixed the bug mate, enjoy!
