### ISSUE TITLE
Question | Should I expect to see performance/memory issue on older devices, for about 30-40 cards?

### ISSUE THREAD

**Issue by roimulia** [saoudrizwan/CardSlider#3]
Should I expect to see performance/memory issue on older devices, for about 30-40 cards?

**Comment by saoudrizwan** [comment]
If by 30-40 cards you mean a few kilobytes of data, then no. Working directly with the file system with such small files is fast. But if you are worried about locking up the main thread, then I would suggest working with Disk in a background thread.
